# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: deeplc-env
channels:
  - openms
  - conda-forge
  - bioconda
dependencies:
  - biopython
  - Click
  - tqdm
  - pyahocorasick
  - pandas
  - matplotlib
  - numpy
  - tensorflow
  - scipy
  - seaborn
  - wget
  - python-wget
  - pip:
      - deeplc
      - ms2pip
      - pyteomics
      - pyopenms
